### ISSUE TITLE
GP Metric Task running on Main Menu

### ISSUE THREAD

**Issue by Zidane** [AlmuraDev/Almura#486]
```java
[15:30:43] [main/ERROR]: The Scheduler tried to run the task griefprevention-S-0 owned by Plugin{id=griefprevention, name=GriefPrevention, version=4.3.0, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=C:\Users\csanders\.gradle\caches\modules-2\files-2.1\me.ryanhamshire\griefprevention\1.12.2-4.3.0.646\4597ab0b4a455c55468dd67e69204b2a433bb976\griefprevention-1.12.2-4.3.0.646.jar}, but an error occured.
java.lang.IllegalStateException: Server has not been initialized yet!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[guava-21.0.jar:?]
	at org.spongepowered.mod.SpongeModGame.getServer(SpongeModGame.java:58) ~[SpongeModGame.class:1.12.2-2705-7.1.0-BETA-3360]
	at org.spongepowered.api.Sponge.getServer(Sponge.java:244) ~[Sponge.class:1.12.2-2705-7.1.0-BETA-3360]
	at me.ryanhamshire.griefprevention.shade.org.bstats.sponge.Metrics.getServerData(Metrics.java:221) ~[Metrics.class:1.12.2-4.3.0.646]
	at me.ryanhamshire.griefprevention.shade.org.bstats.sponge.Metrics.submitData(Metrics.java:256) ~[Metrics.class:1.12.2-4.3.0.646]
	at me.ryanhamshire.griefprevention.shade.org.bstats.sponge.Metrics.access$200(Metrics.java:44) ~[Metrics.class:1.12.2-4.3.0.646]
	at me.ryanhamshire.griefprevention.shade.org.bstats.sponge.Metrics$1.lambda$run$0(Metrics.java:206) ~[Metrics$1.class:1.12.2-4.3.0.646]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2705-7.1.0-BETA-3360]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3360]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3360]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3360]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3360]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_181]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3360]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3360]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2705-7.1.0-BETA-3360]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:360) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3360]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_SpongeMod_onTick_ClientTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1833) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:441) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
```

**Comment by Zidane** [comment]
Closing as this isn't an Almura issue.
