### ISSUE TITLE
The new GUI for the guide has some issues

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/Almura#523]
umm well i tryed to reproduce and this happend
![2018-09-15_20 54 10](https://user-images.githubusercontent.com/39970604/45591789-9fc3b100-b929-11e8-91bf-285576905b33.png)

this is the error for the save or cancel'[20:29:15] [main/INFO]: [CHAT] A problem occured : NullPointerException: null
java.lang.NullPointerException
	at com.almuradev.almura.feature.guide.client.gui.SimplePageView.close(SimplePageView.java:198)
	at net.malisis.core.client.gui.component.interaction.UIButton.executeAction(UIButton.java:352)
	at net.malisis.core.client.gui.component.interaction.UIButton.onClick(UIButton.java:358)
	at net.malisis.core.client.gui.MalisisGui.mouseReleased(MalisisGui.java:504)
	at net.malisis.core.client.gui.MalisisGui.handleMouseInput(MalisisGui.java:353)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:576)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1884)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186)
	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)'

**Comment by Dockter** [comment]
There are zero useful notes on this issue so I cant continue.

**Comment by TherayTharow** [comment]
@dockter it happens when there are
no pages in guide then add a page 
before you click save hit cansel and that will happen

**Comment by Dockter** [comment]
So in single player only you've seen this?

**Comment by TherayTharow** [comment]
yes and this was awille ago

**Comment by PowellA12** [comment]
yes on a test version a while ago

**Comment by TherayTharow** [comment]
@dockter on a test version a while ago just after you added the new guide
